id: IB2834E37
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T19:16:17+00:00'
last_modified: '2022-06-08T13:46:04.408564+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18796
  title: ཕྱུགས་ནད་བརྟག་བཅོས་རྒྱུན་མཁོ་ཕྱོགས་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4DA2:
      image_group_id: I8LS18798
      title: ''
      total_pages: 350
      order: 1
      base_file: 4DA2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
