id: P010460
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18796
  title: ཕྱུགས་ནད་བརྟག་བཅོས་རྒྱུན་མཁོ་ཕྱོགས་བཏུས།
  author: ''
  volumes:
    9403ade4c1a64da5985430287b2e7cba:
      image_group_id: I8LS18798
      title: ''
      volume_number: 1
      total_pages: 350
      base_file: v001.txt
